version: '3'
services:
   api:
      build: ./api
      command: npm run start
      restart: unless-stopped
      ports:
         - "3000:3000"
      environment:
         - PORT=3000
         - HOST=game.l2expert.ru
         - MONGO_URL=mongodb://api_db:27017/api
      depends_on:
         - api_db
   
   api_db:
      image: mongo:latest
         